-- VialXBeauty fresh production schema
-- Safe to run in the dedicated VialXBeauty Supabase project.
-- It creates the tables needed by the current storefront + admin and seeds demo data.

create extension if not exists pgcrypto;

create table if not exists public.shop_settings (
  id bigint primary key default 1,
  shop_name text not null default 'VialXBeauty',
  logo_url text,
  hero_image_url text,
  catalog_image_url text,
  hero_eyebrow text not null default 'VIALXBEAUTY',
  hero_title text not null default 'Premium essentials. Precisely selected.',
  hero_subtitle text not null default 'Explore the VialXBeauty product range with clear details and a simple shopping experience.',
  catalog_eyebrow text not null default 'PRODUCTS',
  catalog_title text not null default 'Shop products',
  catalog_subtitle text not null default 'Find your VialXBeauty essentials.',
  menu_tagline text not null default 'Beauty in a darker shade.',
  facebook_url text,
  tiktok_url text,
  footer_text text default '© VialXBeauty',
  category_order jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.expense_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  amount numeric(12,2) not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null default 0,
  stock integer not null default 0,
  cod_fee numeric(12,2) not null default 0,
  cost_price numeric(12,2) not null default 0,
  category text,
  badge text,
  image_url text,
  description text,
  expense_profile_id bigint references public.expense_profiles(id) on delete set null,
  is_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  name text not null,
  price numeric(12,2) not null default 0,
  stock integer not null default 0,
  badge text,
  image_url text,
  sku text,
  is_default boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  label text not null,
  url text not null,
  section text not null default 'Menu',
  is_visible boolean not null default true,
  open_new_tab boolean not null default false,
  sort_order integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shipping_methods (
  id bigint generated by default as identity primary key,
  name text not null,
  method_type text not null default 'courier',
  description text,
  external_url text,
  button_label text,
  is_active boolean not null default true,
  sort_order integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shipping_fees (
  id bigint generated by default as identity primary key,
  shipping_method_id bigint not null references public.shipping_methods(id) on delete cascade,
  label text not null,
  amount numeric(12,2) not null default 0,
  is_active boolean not null default true,
  sort_order integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_methods (
  id bigint generated by default as identity primary key,
  payment_name text not null,
  short_description text,
  instructions text,
  instructions_visible boolean not null default true,
  cod_fee numeric(12,2) not null default 0,
  receipt_required boolean not null default false,
  reference_required boolean not null default false,
  deposit_required boolean not null default false,
  deposit_percentage numeric(5,2) not null default 0,
  qr_url text,
  is_visible boolean not null default true,
  sort_order integer not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.payment_method_shipping_methods (
  payment_method_id bigint not null references public.payment_methods(id) on delete cascade,
  shipping_method_id bigint not null references public.shipping_methods(id) on delete cascade,
  primary key (payment_method_id, shipping_method_id)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_ref text not null unique,
  customer_name text not null,
  customer_username text,
  phone text,
  email text,
  address text,
  province text,
  city text,
  barangay text,
  street text,
  house_unit text,
  zipcode text,
  payment_method text,
  shipping_method text,
  shipping_method_type text,
  notes text,
  shipping_fee numeric(12,2) not null default 0,
  payment_fee numeric(12,2) not null default 0,
  subtotal numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  amount_paid numeric(12,2) not null default 0,
  payment_status text not null default 'Pending',
  receipt_image text,
  reference_number text,
  paid_at timestamptz,
  status text not null default 'Pending',
  stock_deducted boolean not null default false,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  variant_id bigint references public.product_variants(id) on delete set null,
  variant_name text,
  variant_sku text,
  unit_price numeric(12,2) not null default 0,
  quantity integer not null default 1,
  line_total numeric(12,2) not null default 0,
  created_at timestamptz not null default now()
);

insert into public.shop_settings (id, shop_name, hero_eyebrow, hero_title, hero_subtitle, catalog_eyebrow, catalog_title, catalog_subtitle, menu_tagline, footer_text)
values (1, 'VialXBeauty', 'VIALXBEAUTY', 'Premium essentials. Precisely selected.', 'Explore the VialXBeauty product range with clear details and a simple shopping experience.', 'PRODUCTS', 'Shop products', 'Find your VialXBeauty essentials.', 'Beauty in a darker shade.', '© VialXBeauty')
on conflict (id) do update set
  shop_name = excluded.shop_name,
  hero_eyebrow = excluded.hero_eyebrow,
  hero_title = excluded.hero_title,
  hero_subtitle = excluded.hero_subtitle,
  catalog_eyebrow = excluded.catalog_eyebrow,
  catalog_title = excluded.catalog_title,
  catalog_subtitle = excluded.catalog_subtitle,
  menu_tagline = excluded.menu_tagline,
  footer_text = excluded.footer_text,
  updated_at = now();

insert into public.products (name, price, stock, cost_price, category, badge, description, is_visible)
select 'Radiance Peptide Serum', 1290, 12, 0, 'Serums', 'FEATURED', 'A refined peptide serum for a smooth, luminous-looking finish.', true
where not exists (select 1 from public.products where name = 'Radiance Peptide Serum');

insert into public.products (name, price, stock, cost_price, category, badge, description, is_visible)
select 'Renewal Peptide Complex', 1490, 8, 0, 'Treatments', 'NEW', 'A concentrated beauty treatment designed for a polished daily routine.', true
where not exists (select 1 from public.products where name = 'Renewal Peptide Complex');

insert into public.menu_items (label, url, section, is_visible, open_new_tab, sort_order)
select * from (values
  ('Home', '#home', 'Shop', true, false, 10),
  ('Products', '#shop', 'Shop', true, false, 20)
) as v(label,url,section,is_visible,open_new_tab,sort_order)
where not exists (select 1 from public.menu_items);

insert into public.shipping_methods (name, method_type, description, is_active, sort_order)
select 'Standard delivery', 'courier', 'Standard delivery within the Philippines.', true, 10
where not exists (select 1 from public.shipping_methods where name = 'Standard delivery');

insert into public.shipping_fees (shipping_method_id, label, amount, is_active, sort_order)
select id, 'Metro Manila', 80, true, 10 from public.shipping_methods
where name = 'Standard delivery'
  and not exists (select 1 from public.shipping_fees where label = 'Metro Manila');

insert into public.payment_methods (payment_name, short_description, instructions, instructions_visible, receipt_required, reference_required, is_visible, sort_order)
select 'Cash on Delivery', 'Pay when your order arrives.', 'Please prepare the exact amount when your order arrives.', true, false, false, true, 10
where not exists (select 1 from public.payment_methods where payment_name = 'Cash on Delivery');

insert into public.payment_methods (payment_name, short_description, instructions, instructions_visible, receipt_required, reference_required, is_visible, sort_order)
select 'GCash', 'Pay securely using GCash.', 'Send payment using the GCash details shown at checkout.', true, true, true, true, 20
where not exists (select 1 from public.payment_methods where payment_name = 'GCash');

-- Admin authorization for the VialXBeauty owner account.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select auth.uid() = 'e92620bb-7816-4439-a10d-3e0eeb58ad35'::uuid;
$$;

grant execute on function public.is_admin() to authenticated;

-- Storefront order placement. This function is intentionally the public write path for orders.
create or replace function public.place_storefront_order(p_order jsonb, p_items jsonb)
returns table(order_id text, order_ref text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id uuid;
  v_order_ref text;
  v_item_json jsonb;
begin
  if coalesce(trim(p_order->>'order_ref'), '') = '' then raise exception 'Order reference is required'; end if;
  if jsonb_typeof(p_items) is distinct from 'array' or jsonb_array_length(p_items) = 0 then raise exception 'At least one order item is required'; end if;

  insert into public.orders (
    order_ref, customer_name, customer_username, phone, email, address,
    province, city, barangay, street, house_unit, zipcode, payment_method,
    shipping_method, shipping_method_type, notes, shipping_fee, payment_fee,
    subtotal, total, amount_paid, payment_status, receipt_image,
    reference_number, paid_at, status
  ) values (
    trim(p_order->>'order_ref'), trim(p_order->>'customer_name'),
    nullif(trim(p_order->>'customer_username'), ''), trim(p_order->>'phone'),
    nullif(trim(p_order->>'email'), ''), trim(p_order->>'address'),
    trim(p_order->>'province'), trim(p_order->>'city'), trim(p_order->>'barangay'),
    trim(p_order->>'street'), trim(p_order->>'house_unit'), nullif(trim(p_order->>'zipcode'), ''),
    trim(p_order->>'payment_method'), nullif(trim(p_order->>'shipping_method'), ''),
    nullif(trim(p_order->>'shipping_method_type'), ''), nullif(trim(p_order->>'notes'), ''),
    greatest(coalesce((p_order->>'shipping_fee')::numeric, 0), 0),
    greatest(coalesce((p_order->>'payment_fee')::numeric, 0), 0),
    greatest(coalesce((p_order->>'subtotal')::numeric, 0), 0),
    greatest(coalesce((p_order->>'total')::numeric, 0), 0),
    greatest(coalesce((p_order->>'amount_paid')::numeric, 0), 0),
    'Pending', nullif(p_order->>'receipt_image', ''), nullif(trim(p_order->>'reference_number'), ''),
    nullif(p_order->>'paid_at', '')::timestamptz, 'Pending'
  ) returning id, orders.order_ref into v_order_id, v_order_ref;

  for v_item_json in select value from jsonb_array_elements(p_items) loop
    insert into public.order_items (
      order_id, product_id, product_name, variant_id, variant_name, variant_sku,
      unit_price, quantity, line_total
    ) values (
      v_order_id,
      nullif(v_item_json->>'product_id','')::bigint,
      coalesce(v_item_json->>'product_name',''),
      nullif(v_item_json->>'variant_id','')::bigint,
      nullif(v_item_json->>'variant_name',''),
      nullif(v_item_json->>'variant_sku',''),
      coalesce((v_item_json->>'unit_price')::numeric,0),
      greatest(coalesce((v_item_json->>'quantity')::integer,1),1),
      coalesce((v_item_json->>'line_total')::numeric,0)
    );
  end loop;
  return query select v_order_id::text, v_order_ref::text;
end;
$$;
revoke all on function public.place_storefront_order(jsonb,jsonb) from public;
grant execute on function public.place_storefront_order(jsonb,jsonb) to anon, authenticated;

-- RLS
alter table public.shop_settings enable row level security;
alter table public.products enable row level security;
alter table public.product_variants enable row level security;
alter table public.menu_items enable row level security;
alter table public.shipping_methods enable row level security;
alter table public.shipping_fees enable row level security;
alter table public.payment_methods enable row level security;
alter table public.payment_method_shipping_methods enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.expense_profiles enable row level security;

do $$ begin
  execute 'drop policy if exists shop_settings_public_read on public.shop_settings';
  execute 'drop policy if exists shop_settings_admin_write on public.shop_settings';
  execute 'drop policy if exists products_public_read on public.products';
  execute 'drop policy if exists products_admin_write on public.products';
  execute 'drop policy if exists variants_public_read on public.product_variants';
  execute 'drop policy if exists variants_admin_write on public.product_variants';
  execute 'drop policy if exists menu_public_read on public.menu_items';
  execute 'drop policy if exists menu_admin_write on public.menu_items';
  execute 'drop policy if exists shipping_public_read on public.shipping_methods';
  execute 'drop policy if exists shipping_admin_write on public.shipping_methods';
  execute 'drop policy if exists fees_public_read on public.shipping_fees';
  execute 'drop policy if exists fees_admin_write on public.shipping_fees';
  execute 'drop policy if exists payment_public_read on public.payment_methods';
  execute 'drop policy if exists payment_admin_write on public.payment_methods';
  execute 'drop policy if exists payment_links_public_read on public.payment_method_shipping_methods';
  execute 'drop policy if exists payment_links_admin_write on public.payment_method_shipping_methods';
  execute 'drop policy if exists orders_admin_all on public.orders';
  execute 'drop policy if exists order_items_admin_all on public.order_items';
  execute 'drop policy if exists expense_profiles_admin_all on public.expense_profiles';
end $$;

create policy shop_settings_public_read on public.shop_settings for select using (true);
create policy shop_settings_admin_write on public.shop_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy products_public_read on public.products for select using (is_visible = true or public.is_admin());
create policy products_admin_write on public.products for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy variants_public_read on public.product_variants for select using (is_active = true or public.is_admin());
create policy variants_admin_write on public.product_variants for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy menu_public_read on public.menu_items for select using (is_visible = true or public.is_admin());
create policy menu_admin_write on public.menu_items for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy shipping_public_read on public.shipping_methods for select using (is_active = true or public.is_admin());
create policy shipping_admin_write on public.shipping_methods for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy fees_public_read on public.shipping_fees for select using (is_active = true or public.is_admin());
create policy fees_admin_write on public.shipping_fees for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy payment_public_read on public.payment_methods for select using (is_visible = true or public.is_admin());
create policy payment_admin_write on public.payment_methods for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy payment_links_public_read on public.payment_method_shipping_methods for select using (true);
create policy payment_links_admin_write on public.payment_method_shipping_methods for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy orders_admin_all on public.orders for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy order_items_admin_all on public.order_items for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy expense_profiles_admin_all on public.expense_profiles for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Storage buckets used by the current site.
insert into storage.buckets (id, name, public) values
  ('product-images','product-images',true),
  ('payment-qr','payment-qr',true),
  ('payment-receipts','payment-receipts',false)
on conflict (id) do update set public = excluded.public;

do $$ begin
  execute 'drop policy if exists product_images_public_read on storage.objects';
  execute 'drop policy if exists product_images_admin_write on storage.objects';
  execute 'drop policy if exists payment_qr_public_read on storage.objects';
  execute 'drop policy if exists payment_qr_admin_write on storage.objects';
  execute 'drop policy if exists payment_receipts_admin_read on storage.objects';
  execute 'drop policy if exists payment_receipts_anon_insert on storage.objects';
  execute 'drop policy if exists payment_receipts_admin_delete on storage.objects';
end $$;

create policy product_images_public_read on storage.objects for select using (bucket_id = 'product-images');
create policy product_images_admin_write on storage.objects for all to authenticated using (bucket_id = 'product-images' and public.is_admin()) with check (bucket_id = 'product-images' and public.is_admin());
create policy payment_qr_public_read on storage.objects for select using (bucket_id = 'payment-qr');
create policy payment_qr_admin_write on storage.objects for all to authenticated using (bucket_id = 'payment-qr' and public.is_admin()) with check (bucket_id = 'payment-qr' and public.is_admin());
create policy payment_receipts_anon_insert on storage.objects for insert to anon, authenticated with check (bucket_id = 'payment-receipts');
create policy payment_receipts_admin_read on storage.objects for select to authenticated using (bucket_id = 'payment-receipts' and public.is_admin());
create policy payment_receipts_admin_delete on storage.objects for delete to authenticated using (bucket_id = 'payment-receipts' and public.is_admin());

-- Make the REST schema cache refresh after creating tables.
notify pgrst, 'reload schema';
